# Generated by Django 3.2.5 on 2021-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('api', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название занятия'),
        ),
    ]
